### ISSUE TITLE
Need logical-direction margin properties (and __qem?)

### ISSUE THREAD

**Issue by domenic** [domenic/html-as-custom-elements#40]
For example, in Blink, `<blockquote>` is 

``` css
custom-blockquote {
  display: block;
  -webkit-margin-before: 1__qem;
  -webkit-margin-after: 1em;
  -webkit-margin-start: 40px;
  -webkit-margin-end: 40px;
}
```

As @TabAtkins kindly explained, `-webkit-margin-*` are "logical" versions of the "physical" `margin-{top,right,bottom,left}` properties. This allows blockquotes to work better in different writing modes.

Notably, the HTML spec [does not use these](https://html.spec.whatwg.org/multipage/rendering.html), so I guess the spec is wrong there. Although, it seems possible that if it wasn't for the __qem quirk, we'd be able to just use top/right/bottom/left, since in this case top = bottom and left = right?

There is a very-rough-sketch of standard versions of these properties in ["CSS Logical Properties"](http://dev.w3.org/csswg/css-logical-props). It has been described as "half-copypasted and half-inconsistent (you can decide which half for each part)." ;)
